export const actionTypes = {
    GET_LISTINGS: 'GET_LISTINGS',
    SELECT_LISTING: 'SELECT_LISTING',
    ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES',
    REMOVE_FROM_FAVOURITES: 'REMOVE_FROM_FAVOURITES',
};
