export const actionTypes = {
    GET_LISTINGS: 'GET_LISTINGS',
    GET_LISTINGS_SUCCEEDED: 'GET_LISTINGS_SUCCEEDED',
    GET_LISTINGS_FAILED: 'GET_LISTINGS_FAILED',

    SELECT_LISTING: 'SELECT_LISTING',

    ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES',
    ADD_TO_FAVOURITES_SUCCEEDED: 'ADD_TO_FAVOURITES_SUCCEEDED',
    ADD_TO_FAVOURITES_FAILED: 'ADD_TO_FAVOURITES_FAILED',

    REMOVE_FROM_FAVOURITES: 'REMOVE_FROM_FAVOURITES',
    REMOVE_FROM_FAVOURITES_SUCCEEDED: 'REMOVE_FROM_FAVOURITES_SUCCEEDED',
    REMOVE_FROM_FAVOURITES_FAILED: 'REMOVE_FROM_FAVOURITES_FAILED',
};
